const constants = {
  ROLES: {
    AGENT: 'AGENT',
    OPERATOR: 'OPERATOR',
    MANAGEMENT: 'MANAGEMENT',
  },
  TRANSACTION_TYPES: {
    CASH_IN: 'CASH_IN',
    CASH_OUT: 'CASH_OUT',
  },
  TRANSACTION_STATUSES: {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    CANCELLED: 'CANCELLED',
  },
  ALERT_SEVERITIES: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL',
  },
  ALERT_STATUSES: {
    NEW: 'NEW',
    ASSIGNED: 'ASSIGNED',
    INVESTIGATING: 'INVESTIGATING',
    ESCALATED: 'ESCALATED',
    RESOLVED: 'RESOLVED',
    DISMISSED: 'DISMISSED',
  },
  CASE_PRIORITIES: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL',
  },
  CASE_STATUSES: {
    OPEN: 'OPEN',
    ASSIGNED: 'ASSIGNED',
    IN_PROGRESS: 'IN_PROGRESS',
    ESCALATED: 'ESCALATED',
    RESOLVED: 'RESOLVED',
    CLOSED: 'CLOSED',
  },
  PROVIDER_STATUSES: {
    ACTIVE: 'ACTIVE',
    INACTIVE: 'INACTIVE',
    SUSPENDED: 'SUSPENDED',
  },
  NOTIFICATION_TYPES: {
    ALERT: 'ALERT',
    CASE: 'CASE',
    TRANSACTION: 'TRANSACTION',
    SYSTEM: 'SYSTEM',
  },
  PROVIDER_NAMES: {
    BKASH: 'bkash',
    NAGAD: 'nagad',
    ROCKET: 'rocket',
    UPCOMING: 'upcoming',
  },
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  API_VERSION: 'v1',
};

module.exports = constants;
